permissions:
  contents: write

name: Create Repository ZIP

on:
  push:
    branches:
      - main

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository CanàTV
        uses: actions/checkout@v4

      - name: Create ZIP archive
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          mkdir -p "/tmp/$REPO_NAME"
          rsync -a --exclude=".git" --exclude="*.zip" . "/tmp/$REPO_NAME/"
          cd /tmp
          zip -r "${GITHUB_WORKSPACE}/${REPO_NAME}.zip" "$REPO_NAME/"
          echo "ZIP_NAME=${REPO_NAME}.zip" >> $GITHUB_ENV

      - name: Create or update release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest build
          files: ${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
